---
name: 'issue-metrics'
author: 'github'
description: 'A GitHub Action to report out issue metrics'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/github/issue_metrics:v1'
branding:
  icon: 'check-square'
  color: 'white'
